# Generated by Django 3.2.5 on 2021-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(default=10),
        ),
    ]
