# Generated by Django 3.2.5 on 2021-07-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watcher',
        ),
    ]
