# Generated by Django 3.2.5 on 2021-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('director', models.CharField(max_length=64)),
                ('watcher', models.CharField(max_length=64)),
            ],
        ),
    ]
